Global:
  use_gpu: true
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/pgnet_r50_vd_seal_run/
  save_epoch_step: 300
  eval_batch_step:
  - 0
  - 400
  cal_metric_during_train: false
  pretrained_model: ./pretrain_models/train_step1/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  valid_set: totaltext
  save_res_path: ./output/pgnet_r50_vd_totaltext/predicts_pgnet.txt
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  character_type: EN
  max_text_length: 50
  max_text_nums: 10
  tcl_len: 64
  load_static_weights: false
Architecture:
  model_type: e2e
  algorithm: PGNet
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
  Neck:
    name: PGFPN
  Head:
    name: PGHead
Loss:
  name: PGLoss
  tcl_bs: 32
  max_text_length: 50
  max_text_nums: 10
  pad_num: 6623
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 50
  regularizer:
    name: L2
    factor: 5.0e-05
PostProcess:
  name: PGPostProcess
  score_thresh: 0.5
  mode: fast
Metric:
  name: E2EMetric
  mode: A
  gt_mat_dir: ./train_data/total_text/gt
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  main_indicator: f_score_e2e
Train:
  dataset:
    name: PGDataSet
    data_dir: ./train_data/
    label_file_list:
    - ./train_data/label_2_rotate_transform_final.txt
    - ./train_data/label_3_rotate_transform_final.txt
    ratio_list:
    - 1.0
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - E2ELabelEncodeTrain: null
    - PGProcessTrain:
        batch_size: 5
        min_crop_size: 24
        min_text_size: 4
        max_text_size: 512
    - KeepKeys:
        keep_keys:
        - images
        - tcl_maps
        - tcl_label_maps
        - border_maps
        - direction_maps
        - training_masks
        - label_list
        - pos_list
        - pos_mask
  loader:
    shuffle: true
    drop_last: true
    batch_size_per_card: 5
    num_workers: 16
Eval:
  dataset:
    name: PGDataSet
    data_dir: ./train_data/
    label_file_list:
    - ./train_data/label_test.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - E2ELabelEncodeTest:
        character_dict_path: ppocr/utils/ppocr_keys_v1.txt
    - DetResizeForTest:
        image_shape:
        - 512
        - 512
        padding: true
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - texts
        - ignore_tags
        - img_id
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null
